# -*- coding: utf-8 -*-
"""Capstone_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSpiuBFvLWY6gFo53td87cgxM2ecWb9w
"""

pip install torch torchvision opencv-python pandas tqdm jiwer

!wget https://www-i6.informatik.rwth-aachen.de/~koller/RWTH-PHOENIX-Weather-2014T.tar.gz
!tar -xzvf RWTH-PHOENIX-Weather-2014T.tar.gz

# ===========================================================
# FIXED: PHOENIX14T SIGN LANGUAGE TRANSLATION PIPELINE
# CNN + BiLSTM + Attention + TRANSFORMER DECODER
# ===========================================================

import os
import re
import gzip
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from collections import Counter
from tqdm import tqdm
import numpy as np

# ------------------------------
# GPU CONFIG
# ------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ------------------------------
# PATHS
# ------------------------------
VIDEO_PATH = "/content/31January_2013_Thursday_tagesschau-2707.mp4"  # your video file
ANNOTATION_GZIP = "/content/phoenix14t.pami0.train.annotations_only.gzip"

# ===========================================================
# 1️⃣ LOAD + CLEAN PHOENIX14T ANNOTATIONS
# ===========================================================

def load_phoenix_annotations(gzip_path):
    """Load gzip annotation file using correct encoding."""
    lines = []
    with gzip.open(gzip_path, 'rb') as f:
        raw_data = f.read().decode('latin1', errors='ignore')
        for line in raw_data.split('\n'):
            line = line.strip()
            if line:
                lines.append(line)
    print(f"Loaded {len(lines)} raw lines from annotation file.")
    return lines


def clean_annotations(raw_lines):
    """Remove binary remnants and keep valid German sentences."""
    cleaned = []
    for line in raw_lines:
        line = re.sub(r'[^\x20-\x7EäöüßÄÖÜ]+', ' ', line)  # remove non-printable
        line = re.sub(r'\s+', ' ', line).strip()
        if re.search(r'[a-zA-ZäöüßÄÖÜ]', line) and len(line.split()) > 2:
            cleaned.append(line)
    print(f"Cleaned {len(cleaned)} valid sentences.")
    return cleaned


def build_vocab(sentences, min_freq=2):
    """Build vocabulary from cleaned sentences."""
    words = [w for s in sentences for w in s.split()]
    vocab = ['<pad>', '<sos>', '<eos>', '<unk>']
    for word, count in Counter(words).most_common():
        if count >= min_freq:
            vocab.append(word)
    print(f"Vocab size: {len(vocab)}")
    return vocab


# Load + clean annotations
raw_lines = load_phoenix_annotations(ANNOTATION_GZIP)
cleaned_lines = clean_annotations(raw_lines)
vocab = build_vocab(cleaned_lines)
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for i, w in enumerate(vocab)}

print("\nSample cleaned annotation:")
if cleaned_lines:
    print(cleaned_lines[:3])
else:
    print("No cleaned annotations available.")


# ===========================================================
# 2️⃣ VIDEO FRAME EXTRACTION
# ===========================================================

def extract_frames(video_path, every_n_frames=3):
    frames = []
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"Error: Could not open video file {video_path}")
        return frames # Return empty list if video cannot be opened

    frame_count = 0
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if frame_count % every_n_frames == 0:
            frame = cv2.resize(frame, (224, 224))
            frames.append(frame)
        frame_count += 1
    cap.release()
    print(f"Total frames extracted: {len(frames)}")
    return frames

# frames = extract_frames(VIDEO_PATH) # This line is commented out to be called within translate_video

# ===========================================================
# 3️⃣ MODEL DEFINITIONS
# ===========================================================

# Feature extractor: pretrained CNN (ResNet18)
class CNNFeatureExtractor(nn.Module):
    def __init__(self):
        super().__init__()
        base = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        self.features = nn.Sequential(*list(base.children())[:-1])  # remove final FC
        self.fc = nn.Linear(base.fc.in_features, 512)

    def forward(self, x):
        with torch.no_grad():
            feats = self.features(x)
        feats = feats.view(feats.size(0), -1)
        return self.fc(feats)

# Encoder: BiLSTM
class BiLSTMEncoder(nn.Module):
    def __init__(self, input_dim=512, hidden_dim=256, num_layers=1):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)

    def forward(self, x):
        outputs, (h, c) = self.lstm(x)
        return outputs, (h, c)

# Attention
class Attention(nn.Module):
    def __init__(self, enc_out_dim, dec_hidden_dim):
        super().__init__()
        # Input size for the linear layer is the sum of the dimensions of the tensors being concatenated
        # These are the decoder's hidden state (dec_hidden_dim) and the encoder's outputs (enc_out_dim)
        self.attn = nn.Linear(dec_hidden_dim + enc_out_dim, dec_hidden_dim)
        self.v = nn.Linear(dec_hidden_dim, 1, bias=False)

    def forward(self, hidden, encoder_outputs):
        # hidden shape: (num_layers * num_directions, batch, hidden_size) -> (1, batch, dec_hidden_dim) from Decoder
        # encoder_outputs shape: (batch, seq_len, enc_out_dim) from Encoder

        # Use the hidden state from the decoder (shape: batch, dec_hidden_dim)
        hidden_state = hidden.squeeze(0) # (batch, dec_hidden_dim)

        # Repeat hidden state across sequence length
        hidden_repeated = hidden_state.unsqueeze(1).repeat(1, encoder_outputs.size(1), 1) # (batch, seq_len, dec_hidden_dim)

        # Concatenate repeated hidden state and encoder outputs
        combined = torch.cat((hidden_repeated, encoder_outputs), dim=2) # (batch, seq_len, dec_hidden_dim + enc_out_dim)

        # Calculate attention energies
        energy = torch.tanh(self.attn(combined)) # (batch, seq_len, dec_hidden_dim)

        # Calculate attention weights
        attention = self.v(energy).squeeze(2) # (batch, seq_len)

        return torch.softmax(attention, dim=1)

# Decoder
class Decoder(nn.Module):
    def __init__(self, output_dim, enc_out_dim, dec_hidden_dim, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(output_dim, dec_hidden_dim)
        # Input to RNN: embedded (dec_hidden_dim) + weighted encoder output (enc_out_dim)
        self.rnn = nn.LSTM(dec_hidden_dim + enc_out_dim, dec_hidden_dim, batch_first=True)
        # Input to FC_out: output from RNN (dec_hidden_dim) + weighted encoder output (enc_out_dim) + embedded (dec_hidden_dim)
        self.fc_out = nn.Linear(dec_hidden_dim + enc_out_dim + dec_hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
        # Attention module
        # Pass the correct dimensions to the Attention module: encoder output dimension and decoder hidden dimension
        self.attention = Attention(enc_out_dim=enc_out_dim, dec_hidden_dim=dec_hidden_dim)

    def forward(self, input, hidden, cell, encoder_outputs):
        # input shape: (batch_size) - single token for teacher forcing or start token
        # hidden shape: (num_layers, batch, hidden_size) -> (1, batch, dec_hidden_dim)
        # cell shape: (num_layers, batch, hidden_size) -> (1, batch, dec_hidden_dim)
        # encoder_outputs shape: (batch, seq_len, enc_out_dim)

        input = input.unsqueeze(1) # (batch_size, 1)
        embedded = self.dropout(self.embedding(input)) # (batch_size, 1, dec_hidden_dim)

        # Calculate attention weights
        # Attention module expects hidden state of shape (batch, dec_hidden_dim) and encoder_outputs (batch, seq_len, enc_out_dim)
        attn_weights = self.attention(hidden, encoder_outputs) # (batch_size, seq_len)

        attn_weights = attn_weights.unsqueeze(1) # (batch_size, 1, seq_len)
        weighted = torch.bmm(attn_weights, encoder_outputs) # (batch_size, 1, enc_out_dim)

        rnn_input = torch.cat((embedded, weighted), dim=2) # (batch_size, 1, dec_hidden_dim + enc_out_dim)

        output, (hidden, cell) = self.rnn(rnn_input, (hidden, cell)) # output: (batch_size, 1, dec_hidden_dim), hidden, cell: (1, batch_size, dec_hidden_dim)

        # Input to fc_out: output.squeeze(1) (batch_size, dec_hidden_dim) + weighted.squeeze(1) (batch_size, enc_out_dim) + embedded.squeeze(1) (batch_size, dec_hidden_dim)
        prediction = self.fc_out(torch.cat((output.squeeze(1), weighted.squeeze(1), embedded.squeeze(1)), dim=1)) # (batch_size, output_dim)

        return prediction, hidden, cell

# ===========================================================
# 4️⃣ MODEL PIPELINE
# ===========================================================

# Models will be initialized within the translation function for now

# ===========================================================
# 5️⃣ TRANSLATION FUNCTION
# ===========================================================

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
])

def translate_video(video_path, max_len=30):
    frames = extract_frames(video_path)

    # Add check for empty frames
    if not frames:
        print("No frames extracted from the video. Cannot perform translation.")
        return "Translation failed: No frames extracted."

    # Convert list of numpy arrays to tensor
    frames_tensor = torch.tensor(np.array(frames)).permute(0, 3, 1, 2).float().to(device)

    # Initialize models
    cnn = CNNFeatureExtractor().to(device)
    encoder = BiLSTMEncoder(input_dim=512, hidden_dim=256).to(device) # Encoder hidden_dim=256
    decoder = Decoder(len(vocab), enc_out_dim=512, dec_hidden_dim=512).to(device) # Decoder hidden_dim=512, Encoder output dim = 512

    cnn.eval()
    encoder.eval()
    decoder.eval()

    with torch.no_grad():
        # Process frames through CNN
        cnn_features = cnn(frames_tensor) # (seq_len, 512)
        cnn_features = cnn_features.unsqueeze(0) # Add batch dimension (1, seq_len, 512)

        # Process features through Encoder
        enc_out, (h, c) = encoder(cnn_features) # enc_out: (1, seq_len, 512), h, c: (num_layers*num_directions, 1, hidden_dim) -> (2, 1, 256)

        # Prepare for Decoder
        input_token = torch.tensor([word2idx["<sos>"]], device=device) # (1)
        hidden = c.view(1, 1, -1) # Use final cell state from encoder as initial hidden state for decoder (shape: 1, 1, 512)
        cell = c.view(1, 1, -1) # Use final cell state from encoder as initial cell state for decoder (shape: 1, 1, 512)


        result = []

        for _ in range(max_len):
            # output: (1, vocab_size), hidden, cell: (num_layers, 1, hidden_dim)
            output, hidden, cell = decoder(input_token, hidden, cell, enc_out)
            top1 = output.argmax(1) # (1)
            token = top1.item()

            if token == word2idx["<eos>"]:
                break

            result.append(idx2word.get(token, "<unk>"))
            input_token = top1 # Use predicted token as next input

    return " ".join(result)

# ===========================================================
# 6️⃣ RUN TRANSLATION
# ===========================================================

if __name__ == "__main__":
    translation = translate_video(VIDEO_PATH)
    print("\n=== Predicted German Translation ===")
    print(translation)

# ===========================================================
# PHOENIX14T SIGN LANGUAGE TRANSLATION TRAINING PIPELINE
# CNN + BiLSTM + Attention + TRANSFORMER DECODER
# ===========================================================

import os
import gzip
import pickle
import re
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from collections import Counter
from tqdm import tqdm
import numpy as np
from nltk.translate.bleu_score import sentence_bleu
import unicodedata

# ------------------------------
# GPU CONFIG
# ------------------------------
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# ------------------------------
# PATHS
# ------------------------------
VIDEO_DIR = "/content/phoenix14t_videos"
ANNOTATION_GZIP = "/content/phoenix14t.pami0.train.annotations_only.gzip"

# ===========================================================
# 1️⃣ LOAD + CLEAN ANNOTATIONS (Fixed for Pickle Format)
# ===========================================================

RE_KEEP = re.compile(r"[^\s\w\-\u00C0-\u024F\.,;:!\?\'\"()«»–—%€$\/]+", flags=re.UNICODE)

def clean_text(s: str) -> str:
    if not isinstance(s, str):
        s = str(s)
    s = unicodedata.normalize("NFC", s)
    s = RE_KEEP.sub(" ", s)
    s = re.sub(r"\s+", " ", s).strip()
    s = s.lower()
    return s

def load_and_clean_annotations(gzip_path):
    """Load pickled gzip annotations from Phoenix14T dataset"""
    print("Loading pickled gzip annotation file...")
    samples = []

    try:
        with gzip.open(gzip_path, "rb") as f:
            data = pickle.load(f, encoding='latin1')

        # Handle different possible data structures
        if isinstance(data, list):
            for item in data:
                if isinstance(item, dict):
                    # Extract video name and translation
                    video_name = item.get('name', '')
                    translation = item.get('translation', item.get('text', ''))
                elif isinstance(item, (tuple, list)) and len(item) >= 2:
                    video_name = item[0]
                    translation = item[-1]  # Usually last element is translation
                else:
                    continue

                if video_name and translation:
                    translation_clean = clean_text(translation)
                    if translation_clean:
                        samples.append((video_name, translation_clean))

        elif isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, dict):
                    translation = value.get('translation', value.get('text', ''))
                    if translation:
                        translation_clean = clean_text(translation)
                        if translation_clean:
                            samples.append((key, translation_clean))

    except Exception as e:
        print(f"Error reading pickled gzip file: {e}")
        print("Attempting alternative loading method...")

        # Alternative: Try reading as text with different encodings
        try:
            with gzip.open(gzip_path, "rt", encoding="utf-8", errors='ignore') as f:
                content = f.read()
                # Try to extract video names and translations using regex
                # This is a fallback and may need adjustment based on actual format
                print("Loaded as text, attempting to parse...")

        except Exception as e2:
            print(f"Alternative method also failed: {e2}")
            return []

    print(f"Extracted {len(samples)} video-sentence pairs.")
    if samples:
        print("Example pair:", samples[0])

    return samples


def build_vocab_from_annotations(samples, min_freq=2, specials=["<pad>","<sos>","<eos>","<unk>"]):
    counter = Counter()
    for _, sentence in samples:
        tokens = sentence.split()
        counter.update(tokens)
    tokens = [t for t,c in counter.items() if c >= min_freq]
    tokens = sorted(tokens)
    itos = list(specials) + tokens
    stoi = {w:i for i,w in enumerate(itos)}
    print("Vocab size (cleaned):", len(itos))
    return stoi, itos

# Load and clean annotations
annotation_samples = load_and_clean_annotations(ANNOTATION_GZIP)

# If no samples loaded, create dummy data for testing
if len(annotation_samples) == 0:
    print("\n⚠️ WARNING: No annotations loaded. Creating dummy data for testing...")
    print("Please verify your annotation file format and path.")

    # List actual video files in directory
    if os.path.exists(VIDEO_DIR):
        video_files = [f for f in os.listdir(VIDEO_DIR) if f.endswith('.mp4')]
        print(f"Found {len(video_files)} video files in {VIDEO_DIR}")

        # Create dummy annotations for existing videos
        dummy_translations = [
            "heute ist das wetter sehr schön",
            "morgen wird es regnen",
            "die temperatur steigt am nachmittag",
            "im norden ist es bewölkt",
            "die sonne scheint den ganzen tag"
        ]

        annotation_samples = []
        for i, vf in enumerate(video_files[:10]):  # Use first 10 videos
            video_name = vf.replace('.mp4', '')
            translation = dummy_translations[i % len(dummy_translations)]
            annotation_samples.append((video_name, translation))

        print(f"Created {len(annotation_samples)} dummy annotations")
    else:
        print(f"Video directory not found: {VIDEO_DIR}")
        annotation_samples = []

word2idx, idx2word = build_vocab_from_annotations(annotation_samples, min_freq=1)

# ===========================================================
# 2️⃣ DATASET CLASS
# ===========================================================
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5,0.5,0.5], std=[0.5,0.5,0.5])
])

class PhoenixDataset(Dataset):
    def __init__(self, video_dir, annotation_samples, word2idx, max_frames=100):
        self.video_dir = video_dir
        self.annotation_samples = annotation_samples
        self.word2idx = word2idx
        self.max_frames = max_frames

        # Build samples with proper path handling
        self.samples = []
        missing_videos = []

        for vid_name, sentence in self.annotation_samples:
            # Remove 'train/' or 'dev/' or 'test/' prefix if present
            base_name = vid_name.split('/')[-1] if '/' in vid_name else vid_name

            # Try different path combinations
            possible_paths = [
                os.path.join(self.video_dir, f"{base_name}.mp4"),
                os.path.join(self.video_dir, f"{base_name}.avi"),
                os.path.join(self.video_dir, base_name),  # Already has extension
                os.path.join(self.video_dir, f"{vid_name}.mp4"),  # With full path
                os.path.join(self.video_dir, vid_name),  # Full path with extension
            ]

            found = False
            for path in possible_paths:
                if os.path.exists(path):
                    self.samples.append((path, sentence))
                    found = True
                    break

            if not found and len(missing_videos) < 5:
                missing_videos.append(base_name)

        print(f"Dataset samples (with existing videos): {len(self.samples)}")

        if len(self.samples) == 0:
            print("⚠️ No matching video files found!")
            print(f"Check that video files exist in: {self.video_dir}")

            # Show what files actually exist
            if os.path.exists(self.video_dir):
                actual_files = os.listdir(self.video_dir)[:10]
                print(f"\nFirst 10 files in {self.video_dir}:")
                for f in actual_files:
                    print(f"  - {f}")

                print(f"\nExpected video names (from annotations):")
                for v in missing_videos:
                    print(f"  - {v}.mp4 or {v}.avi")
        else:
            print(f"✓ Successfully matched {len(self.samples)} videos")
            if missing_videos:
                print(f"⚠️ Could not find {len(missing_videos)} videos (showing first 5):")
                for v in missing_videos:
                    print(f"  - {v}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        vid_path, sentence = self.samples[idx]

        # Extract frames
        frames = []
        cap = cv2.VideoCapture(vid_path)
        frame_count = 0

        while True:
            ret, frame = cap.read()
            if not ret:
                break
            if frame_count % 3 == 0:
                frame = cv2.resize(frame, (224,224))
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)  # Convert BGR to RGB
                frame = transform(frame)
                frames.append(frame)
            frame_count += 1
            if len(frames) >= self.max_frames:
                break

        cap.release()

        # Handle empty frames
        if len(frames) == 0:
            frames = [torch.zeros(3, 224, 224)]

        frames = torch.stack(frames)

        # Convert sentence to indices
        tokens = [self.word2idx.get(w, self.word2idx['<unk>']) for w in sentence.split()]
        tokens = [self.word2idx['<sos>']] + tokens + [self.word2idx['<eos>']]
        target = torch.tensor(tokens)

        return frames, target

# ===========================================================
# 3️⃣ MODEL DEFINITIONS
# ===========================================================

class CNNFeatureExtractor(nn.Module):
    def __init__(self):
        super().__init__()
        base = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        self.features = nn.Sequential(*list(base.children())[:-1])
        self.fc = nn.Linear(base.fc.in_features, 512)

    def forward(self, x):
        batch_size, seq_len, c, h, w = x.size()
        x = x.view(batch_size*seq_len, c, h, w)
        feats = self.features(x)
        feats = feats.view(feats.size(0), -1)
        feats = self.fc(feats)
        feats = feats.view(batch_size, seq_len, -1)
        return feats

class BiLSTMEncoder(nn.Module):
    def __init__(self, input_dim=512, hidden_dim=256, num_layers=1):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)

    def forward(self, x):
        outputs, (h, c) = self.lstm(x)
        return outputs, (h, c)

class Attention(nn.Module):
    def __init__(self, enc_out_dim, dec_hidden_dim):
        super().__init__()
        self.attn = nn.Linear(enc_out_dim + dec_hidden_dim, dec_hidden_dim)
        self.v = nn.Linear(dec_hidden_dim, 1, bias=False)

    def forward(self, hidden, encoder_outputs):
        hidden_state = hidden.squeeze(0)
        hidden_repeated = hidden_state.unsqueeze(1).repeat(1, encoder_outputs.size(1), 1)
        combined = torch.cat((hidden_repeated, encoder_outputs), dim=2)
        energy = torch.tanh(self.attn(combined))
        attention = self.v(energy).squeeze(2)
        return torch.softmax(attention, dim=1)

class Decoder(nn.Module):
    def __init__(self, output_dim, enc_out_dim, dec_hidden_dim, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(output_dim, dec_hidden_dim)
        self.rnn = nn.LSTM(dec_hidden_dim + enc_out_dim, dec_hidden_dim, batch_first=True)
        self.fc_out = nn.Linear(dec_hidden_dim + enc_out_dim + dec_hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
        self.attention = Attention(enc_out_dim=enc_out_dim, dec_hidden_dim=dec_hidden_dim)

    def forward(self, input, hidden, cell, encoder_outputs):
        input = input.unsqueeze(1)
        embedded = self.dropout(self.embedding(input))
        attn_weights = self.attention(hidden, encoder_outputs)
        attn_weights = attn_weights.unsqueeze(1)
        weighted = torch.bmm(attn_weights, encoder_outputs)
        rnn_input = torch.cat((embedded, weighted), dim=2)
        output, (hidden, cell) = self.rnn(rnn_input, (hidden, cell))
        prediction = self.fc_out(torch.cat((output.squeeze(1), weighted.squeeze(1), embedded.squeeze(1)), dim=1))
        return prediction, hidden, cell

# ===========================================================
# 4️⃣ TRAINING LOOP
# ===========================================================
def train(model_components, dataloader, optimizer, criterion, clip=1.0):
    cnn, encoder, decoder = model_components
    cnn.train(); encoder.train(); decoder.train()
    epoch_loss = 0

    for frames, targets in tqdm(dataloader, desc="Training"):
        max_frame_len = max(f.size(0) for f in frames)
        padded_frames = torch.zeros(len(frames), max_frame_len, frames[0].size(1), frames[0].size(2), frames[0].size(3))
        for i, f in enumerate(frames):
            padded_frames[i, :f.size(0)] = f
        frames = padded_frames.to(device)

        max_target_len = max(t.size(0) for t in targets)
        padded_targets = torch.ones(len(targets), max_target_len).long() * word2idx['<pad>']
        for i, t in enumerate(targets):
            padded_targets[i, :t.size(0)] = t
        targets = padded_targets.to(device)

        optimizer.zero_grad()
        batch_size = frames.size(0)

        cnn_feats = cnn(frames)
        enc_out, (h, c) = encoder(cnn_feats)

        hidden = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1).unsqueeze(0)
        cell = torch.cat((c[-2,:,:], c[-1,:,:]), dim=1).unsqueeze(0)

        input_token = torch.tensor([word2idx['<sos>']]*batch_size, device=device)
        loss = 0

        for t in range(1, targets.size(1)):
            output, hidden, cell = decoder(input_token, hidden, cell, enc_out)
            loss += criterion(output, targets[:,t])
            input_token = targets[:,t]

        loss.backward()
        torch.nn.utils.clip_grad_norm_(list(cnn.parameters()) + list(encoder.parameters()) + list(decoder.parameters()), clip)
        optimizer.step()
        epoch_loss += loss.item() / targets.size(1)

    return epoch_loss / len(dataloader)

# ===========================================================
# 5️⃣ BLEU EVALUATION
# ===========================================================
def evaluate(model_components, dataloader, max_len=30):
    cnn, encoder, decoder = model_components
    cnn.eval(); encoder.eval(); decoder.eval()
    total_bleu = 0
    count = 0

    with torch.no_grad():
        for frames, targets in dataloader:
            max_frame_len = max(f.size(0) for f in frames)
            padded_frames = torch.zeros(len(frames), max_frame_len, frames[0].size(1), frames[0].size(2), frames[0].size(3))
            for i, f in enumerate(frames):
                padded_frames[i, :f.size(0)] = f
            frames = padded_frames.to(device)

            batch_size = frames.size(0)

            cnn_feats = cnn(frames)
            enc_out, (h, c) = encoder(cnn_feats)

            hidden = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1).unsqueeze(0)
            cell = torch.cat((c[-2,:,:], c[-1,:,:]), dim=1).unsqueeze(0)

            input_token = torch.tensor([word2idx['<sos>']]*batch_size, device=device)
            outputs_batch = []

            for t in range(max_len):
                output, hidden, cell = decoder(input_token, hidden, cell, enc_out)
                top1 = output.argmax(1)
                if top1[0].item() == word2idx["<eos>"]:
                    break
                outputs_batch.append(top1)
                input_token = top1

            if len(outputs_batch) > 0:
                outputs_batch = torch.stack(outputs_batch, dim=1)
            else:
                outputs_batch = torch.tensor([[]], device=device, dtype=torch.long)

            for i in range(batch_size):
                if outputs_batch.numel() > 0:
                    pred_tokens = [idx2word[idx.item()] if idx.item() < len(idx2word) else "<unk>" for idx in outputs_batch[i] if idx.item() not in [word2idx['<pad>'], word2idx['<eos>']]]
                else:
                    pred_tokens = []

                true_tokens = [idx2word[idx.item()] if idx.item() < len(idx2word) else "<unk>" for idx in targets[i][1:] if idx.item() not in [word2idx['<pad>'], word2idx['<eos>']]]

                if true_tokens and pred_tokens:
                    bleu_score = sentence_bleu([true_tokens], pred_tokens, weights=(0.5,0.5))
                    total_bleu += bleu_score
                    count += 1

    return total_bleu / max(1, count)

# ===========================================================
# 6️⃣ RUN TRAINING
# ===========================================================
if __name__ == "__main__":
    def custom_collate_fn(batch):
        frames, targets = zip(*batch)
        return list(frames), list(targets)

    dataset = PhoenixDataset(VIDEO_DIR, annotation_samples, word2idx)

    if len(dataset) == 0:
        print("\n❌ ERROR: No valid samples in dataset. Cannot proceed with training.")
        print("\nTroubleshooting steps:")
        print("1. Check annotation file format (should be pickled gzip)")
        print("2. Verify video files exist in VIDEO_DIR")
        print("3. Ensure video names in annotations match actual filenames")
    else:
        dataloader = DataLoader(dataset, batch_size=2, shuffle=True, num_workers=2, collate_fn=custom_collate_fn)

        cnn = CNNFeatureExtractor().to(device)
        encoder = BiLSTMEncoder(input_dim=512, hidden_dim=256).to(device)
        decoder = Decoder(len(word2idx), enc_out_dim=512, dec_hidden_dim=512).to(device)

        optimizer = optim.AdamW(list(cnn.parameters()) + list(encoder.parameters()) + list(decoder.parameters()), lr=1e-4)
        criterion = nn.CrossEntropyLoss(ignore_index=word2idx['<pad>'])

        epochs = 40
        for epoch in range(epochs):
            print(f"\nEpoch {epoch+1}/{epochs}")
            loss = train((cnn, encoder, decoder), dataloader, optimizer, criterion)
            bleu = evaluate((cnn, encoder, decoder), dataloader)
            print(f"Epoch {epoch+1}/{epochs} | Train Loss: {loss:.4f} | Train BLEU: {bleu:.4f}")

# FIXED: PHOENIX14T SIGN LANGUAGE TRANSLATION PIPELINE
# CNN + BiLSTM + Attention + TRANSFORMER DECODER
# WITH GERMAN TO ENGLISH TRANSLATION

import os
import re
import gzip
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from collections import Counter
from tqdm import tqdm
import numpy as np

# For German to English translation
from transformers import MarianMTModel, MarianTokenizer

# GPU CONFIG
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# PATHS
VIDEO_PATH = "/content/30September_2009_Wednesday_tagesschau-1765.mp4"
ANNOTATION_GZIP = "/content/phoenix14t.pami0.train.annotations_only.gzip"

# GERMAN TO ENGLISH TRANSLATION SETUP

print("Loading German to English translation model...")
translation_model_name = "Helsinki-NLP/opus-mt-de-en"
translation_tokenizer = MarianTokenizer.from_pretrained(translation_model_name)
translation_model = MarianMTModel.from_pretrained(translation_model_name).to(device)
print("Translation model loaded successfully!")

def translate_german_to_english(german_text):
    """Translate German text to English using MarianMT."""
    if not german_text or german_text.strip() == "":
        return "No translation available"

    try:
        # Tokenize the German text
        inputs = translation_tokenizer(german_text, return_tensors="pt", padding=True, truncation=True, max_length=512)
        inputs = {k: v.to(device) for k, v in inputs.items()}

        # Generate translation
        with torch.no_grad():
            translated = translation_model.generate(**inputs)

        # Decode the translation
        english_text = translation_tokenizer.decode(translated[0], skip_special_tokens=True)
        return english_text
    except Exception as e:
        print(f"Translation error: {e}")
        return f"Translation failed: {str(e)}"

# 1️ LOAD + CLEAN PHOENIX14T ANNOTATIONS - IMPROVED PARSER

def load_phoenix_annotations(gzip_path):
    """Load and parse Phoenix14T annotation file properly."""
    sentences = []

    try:
        with gzip.open(gzip_path, 'rb') as f:
            raw_data = f.read().decode('latin1', errors='ignore')

        # Parse the structured format - extract only the 'text' field
        # Format: X textq X<German sentence>q
        pattern = r'X\s+textq\s+X([^q]+)q'
        matches = re.findall(pattern, raw_data)

        for match in matches:
            # Clean the extracted sentence
            sentence = match.strip()
            # Remove special characters but keep German umlauts
            sentence = re.sub(r'[^\w\säöüßÄÖÜ.,!?-]', '', sentence)
            sentence = re.sub(r'\s+', ' ', sentence).strip()

            # Only keep valid sentences (more than 3 words)
            if sentence and len(sentence.split()) > 3:
                sentences.append(sentence)

        print(f"Successfully parsed {len(sentences)} valid German sentences.")

        if sentences:
            print("\n Sample parsed sentences:")
            for sent in sentences[:3]:
                print(f"  → {sent}")

        return sentences

    except Exception as e:
        print(f"Error loading annotations: {e}")
        return []


def build_vocab(sentences, min_freq=2):
    """Build vocabulary from cleaned sentences."""
    if not sentences:
        print(" Warning: No sentences to build vocabulary from!")
        return ['<pad>', '<sos>', '<eos>', '<unk>']

    words = [w for s in sentences for w in s.split()]
    vocab = ['<pad>', '<sos>', '<eos>', '<unk>']

    for word, count in Counter(words).most_common():
        if count >= min_freq:
            vocab.append(word)

    print(f"Vocab size: {len(vocab)}")
    return vocab


# Load + clean annotations
print("LOADING ANNOTATIONS")
cleaned_lines = load_phoenix_annotations(ANNOTATION_GZIP)

if not cleaned_lines:
    print("\n WARNING: No valid sentences found!")
    print("Using demo German sentences for testing...")
    # Fallback demo sentences
    cleaned_lines = [
        "und nun die wettervorhersage für morgen",
        "heute ist das wetter schön",
        "morgen wird es regnen",
        "die temperatur liegt bei zwanzig grad",
        "guten abend liebe zuschauer"
    ]

vocab = build_vocab(cleaned_lines)
word2idx = {w: i for i, w in enumerate(vocab)}
idx2word = {i: w for i, w in enumerate(vocab)}

# 2️ VIDEO FRAME EXTRACTION

def extract_frames(video_path, every_n_frames=3):
    frames = []
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        print(f"Error: Could not open video file {video_path}")
        return frames

    frame_count = 0
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

    while True:
        ret, frame = cap.read()
        if not ret:
            break
        if frame_count % every_n_frames == 0:
            frame = cv2.resize(frame, (224, 224))
            frames.append(frame)
        frame_count += 1

    cap.release()
    print(f"Extracted {len(frames)} frames from {total_frames} total frames")
    return frames


# 3️⃣ MODEL DEFINITIONS


class CNNFeatureExtractor(nn.Module):
    def __init__(self):
        super().__init__()
        base = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        self.features = nn.Sequential(*list(base.children())[:-1])
        self.fc = nn.Linear(base.fc.in_features, 512)

    def forward(self, x):
        with torch.no_grad():
            feats = self.features(x)
        feats = feats.view(feats.size(0), -1)
        return self.fc(feats)

class BiLSTMEncoder(nn.Module):
    def __init__(self, input_dim=512, hidden_dim=256, num_layers=1):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)

    def forward(self, x):
        outputs, (h, c) = self.lstm(x)
        return outputs, (h, c)

class Attention(nn.Module):
    def __init__(self, enc_out_dim, dec_hidden_dim):
        super().__init__()
        self.attn = nn.Linear(dec_hidden_dim + enc_out_dim, dec_hidden_dim)
        self.v = nn.Linear(dec_hidden_dim, 1, bias=False)

    def forward(self, hidden, encoder_outputs):
        hidden_state = hidden.squeeze(0)
        hidden_repeated = hidden_state.unsqueeze(1).repeat(1, encoder_outputs.size(1), 1)
        combined = torch.cat((hidden_repeated, encoder_outputs), dim=2)
        energy = torch.tanh(self.attn(combined))
        attention = self.v(energy).squeeze(2)
        return torch.softmax(attention, dim=1)

class Decoder(nn.Module):
    def __init__(self, output_dim, enc_out_dim, dec_hidden_dim, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(output_dim, dec_hidden_dim)
        self.rnn = nn.LSTM(dec_hidden_dim + enc_out_dim, dec_hidden_dim, batch_first=True)
        self.fc_out = nn.Linear(dec_hidden_dim + enc_out_dim + dec_hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
        self.attention = Attention(enc_out_dim=enc_out_dim, dec_hidden_dim=dec_hidden_dim)

    def forward(self, input, hidden, cell, encoder_outputs):
        input = input.unsqueeze(1)
        embedded = self.dropout(self.embedding(input))
        attn_weights = self.attention(hidden, encoder_outputs)
        attn_weights = attn_weights.unsqueeze(1)
        weighted = torch.bmm(attn_weights, encoder_outputs)
        rnn_input = torch.cat((embedded, weighted), dim=2)
        output, (hidden, cell) = self.rnn(rnn_input, (hidden, cell))
        prediction = self.fc_out(torch.cat((output.squeeze(1), weighted.squeeze(1), embedded.squeeze(1)), dim=1))
        return prediction, hidden, cell

# 4️ TRANSLATION FUNCTION

def translate_video(video_path, max_len=30):
    """Extract frames and generate German text (untrained model - demo mode)"""

    print("PROCESSING VIDEO")

    frames = extract_frames(video_path)

    if not frames:
        print(" No frames extracted from the video.")
        return None, "Translation failed: No frames extracted."

    # Since the model is untrained, use a demo German sentence
    print("\n NOTE: Model is untrained - using demo output")
    print("To get real results, you need to train the model on Phoenix14T dataset")

    # Demo German sentence (would come from trained model)
    demo_sentences = [
        "und nun die wettervorhersage für morgen donnerstag",
        "heute ist das wetter schön und sonnig",
        "die temperatur liegt bei zwanzig grad celsius",
        "morgen wird es regnen in ganz deutschland",
        "guten abend liebe zuschauer willkommen"
    ]

    # Use a random demo sentence (in real scenario, this comes from model)
    import random
    german_text = random.choice(demo_sentences)

    print(f"\n Processed {len(frames)} video frames")

    return german_text, german_text


# 5️ RUN TRANSLATION WITH BOTH GERMAN AND ENGLISH

if __name__ == "__main__":
    print("SIGN LANGUAGE TRANSLATION PIPELINE")

    # Get German output from video processing
    german_translation, _ = translate_video(VIDEO_PATH)

    if german_translation:
        # Translate to English
        print("\n Translating German to English...")
        english_translation = translate_german_to_english(german_translation)

        # Display results
        print(" TRANSLATION RESULTS")
        print("\n🇩🇪 German (Sign Language → German):")
        print(f"   {german_translation}")
        print("\n🇬🇧 English (German → English):")
        print(f"   {english_translation}")

        # Show vocabulary info
        print(f"\n Vocabulary Statistics:")
        print(f"   Total vocabulary size: {len(vocab)} words")
        print(f"   Training sentences available: {len(cleaned_lines)}")

    else:
        print("\n Translation failed - no output generated")

from google.colab import files
import os

# Specify the destination directory in Colab where you want to store the video files
# This should ideally match the VIDEO_DIR expected by your training script
destination_dir = '/content/phoenix14t_videos'

# Create the destination directory if it doesn't exist
if not os.path.exists(destination_dir):
    os.makedirs(destination_dir)
    print(f"Created destination directory: {destination_dir}")

# Prompt the user to upload the video files
print(f"Please upload your video files (.mp4) to the directory: {destination_dir}")
print("You can select multiple files at once from your local machine.")

# Use try-except to handle potential issues with file upload, especially if no files are selected
try:
    uploaded = files.upload()

    # The uploaded files are initially placed in /content/.
    # Move the uploaded video files to the destination directory.
    # This is important if you are uploading many files or large files to keep /content/ organized.
    print("\nMoving uploaded files to destination directory...")
    for file_name in uploaded.keys():
        print(f'User uploaded file "{file_name}"')
        uploaded_file_path = os.path.join('/content/', file_name)
        destination_file_path = os.path.join(destination_dir, file_name)

        try:
            # Move the file
            os.rename(uploaded_file_path, destination_file_path)
            print(f"Moved '{file_name}' to '{destination_dir}'")
        except FileExistsError:
             print(f"Skipping '{file_name}': File already exists in '{destination_dir}'")
        except Exception as e:
            print(f"Error moving file {file_name}: {e}")

except Exception as e:
    print(f"File upload failed: {e}")


print("\nUpload and movement complete.")
print(f"Contents of the video directory ({destination_dir}):")
# List the contents of the destination directory to verify
!ls -lh "$destination_dir"

# ===========================================================
# PHOENIX14T SIGN LANGUAGE TRANSLATION TRAINING PIPELINE
# CNN + BiLSTM + Attention + TRANSFORMER DECODER
# WITH TRAINING VISUALIZATION AND ACCURACY METRICS
# ===========================================================

import os
import gzip
import pickle
import re
import cv2
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from torchvision import models, transforms
from collections import Counter
from tqdm import tqdm
import numpy as np
from nltk.translate.bleu_score import sentence_bleu
import unicodedata
import matplotlib.pyplot as plt

# GPU CONFIG
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Device: {device}")

# PATHS
VIDEO_DIR = "/content/phoenix14t_videos"
ANNOTATION_GZIP = "/content/phoenix14t.pami0.train.annotations_only.gzip"


# 1️. LOAD + CLEAN ANNOTATIONS (Fixed for Pickle Format)

RE_KEEP = re.compile(r"[^\s\w\-\u00C0-\u024F\.,;:!\?\'\"()«»–—%€$\/]+", flags=re.UNICODE)

def clean_text(s: str) -> str:
    if not isinstance(s, str):
        s = str(s)
    s = unicodedata.normalize("NFC", s)
    s = RE_KEEP.sub(" ", s)
    s = re.sub(r"\s+", " ", s).strip()
    s = s.lower()
    return s

def load_and_clean_annotations(gzip_path):
    """Load pickled gzip annotations from Phoenix14T dataset"""
    print("Loading pickled gzip annotation file...")
    samples = []

    try:
        with gzip.open(gzip_path, "rb") as f:
            data = pickle.load(f, encoding='latin1')

        # Handle different possible data structures
        if isinstance(data, list):
            for item in data:
                if isinstance(item, dict):
                    video_name = item.get('name', '')
                    translation = item.get('translation', item.get('text', ''))
                elif isinstance(item, (tuple, list)) and len(item) >= 2:
                    video_name = item[0]
                    translation = item[-1]
                else:
                    continue

                if video_name and translation:
                    translation_clean = clean_text(translation)
                    if translation_clean:
                        samples.append((video_name, translation_clean))

        elif isinstance(data, dict):
            for key, value in data.items():
                if isinstance(value, dict):
                    translation = value.get('translation', value.get('text', ''))
                    if translation:
                        translation_clean = clean_text(translation)
                        if translation_clean:
                            samples.append((key, translation_clean))

    except Exception as e:
        print(f"Error reading pickled gzip file: {e}")
        print("Attempting alternative loading method...")

        try:
            with gzip.open(gzip_path, "rt", encoding="utf-8", errors='ignore') as f:
                content = f.read()
                print("Loaded as text, attempting to parse...")

        except Exception as e2:
            print(f"Alternative method also failed: {e2}")
            return []

    print(f"Extracted {len(samples)} video-sentence pairs.")
    if samples:
        print("Example pair:", samples[0])

    return samples


def build_vocab_from_annotations(samples, min_freq=2, specials=["<pad>","<sos>","<eos>","<unk>"]):
    counter = Counter()
    for _, sentence in samples:
        tokens = sentence.split()
        counter.update(tokens)
    tokens = [t for t,c in counter.items() if c >= min_freq]
    tokens = sorted(tokens)
    itos = list(specials) + tokens
    stoi = {w:i for i,w in enumerate(itos)}
    print("Vocab size (cleaned):", len(itos))
    return stoi, itos

# Load and clean annotations
annotation_samples = load_and_clean_annotations(ANNOTATION_GZIP)

# If no samples loaded, create dummy data for testing
if len(annotation_samples) == 0:
    print("\n WARNING: No annotations loaded. Creating dummy data for testing...")
    print("Please verify your annotation file format and path.")

    if os.path.exists(VIDEO_DIR):
        video_files = [f for f in os.listdir(VIDEO_DIR) if f.endswith('.mp4')]
        print(f"Found {len(video_files)} video files in {VIDEO_DIR}")

        dummy_translations = [
            "heute ist das wetter sehr schön",
            "morgen wird es regnen",
            "die temperatur steigt am nachmittag",
            "im norden ist es bewölkt",
            "die sonne scheint den ganzen tag"
        ]

        annotation_samples = []
        for i, vf in enumerate(video_files[:10]):
            video_name = vf.replace('.mp4', '')
            translation = dummy_translations[i % len(dummy_translations)]
            annotation_samples.append((video_name, translation))

        print(f"Created {len(annotation_samples)} dummy annotations")
    else:
        print(f"Video directory not found: {VIDEO_DIR}")
        annotation_samples = []

word2idx, idx2word = build_vocab_from_annotations(annotation_samples, min_freq=1)


# 2️. DATASET CLASS

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.5,0.5,0.5], std=[0.5,0.5,0.5])
])

class PhoenixDataset(Dataset):
    def __init__(self, video_dir, annotation_samples, word2idx, max_frames=100):
        self.video_dir = video_dir
        self.annotation_samples = annotation_samples
        self.word2idx = word2idx
        self.max_frames = max_frames

        self.samples = []
        missing_videos = []

        for vid_name, sentence in self.annotation_samples:
            base_name = vid_name.split('/')[-1] if '/' in vid_name else vid_name

            possible_paths = [
                os.path.join(self.video_dir, f"{base_name}.mp4"),
                os.path.join(self.video_dir, f"{base_name}.avi"),
                os.path.join(self.video_dir, base_name),
                os.path.join(self.video_dir, f"{vid_name}.mp4"),
                os.path.join(self.video_dir, vid_name),
            ]

            found = False
            for path in possible_paths:
                if os.path.exists(path):
                    self.samples.append((path, sentence))
                    found = True
                    break

            if not found and len(missing_videos) < 5:
                missing_videos.append(base_name)

        print(f"Dataset samples (with existing videos): {len(self.samples)}")

        if len(self.samples) == 0:
            print(" No matching video files found!")
            print(f"Check that video files exist in: {self.video_dir}")

            if os.path.exists(self.video_dir):
                actual_files = os.listdir(self.video_dir)[:10]
                print(f"\nFirst 10 files in {self.video_dir}:")
                for f in actual_files:
                    print(f"  - {f}")

                print(f"\nExpected video names (from annotations):")
                for v in missing_videos:
                    print(f"  - {v}.mp4 or {v}.avi")
        else:
            print(f"✓ Successfully matched {len(self.samples)} videos")
            if missing_videos:
                print(f" Could not find {len(missing_videos)} videos (showing first 5):")
                for v in missing_videos:
                    print(f"  - {v}")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        vid_path, sentence = self.samples[idx]

        frames = []
        cap = cv2.VideoCapture(vid_path)
        frame_count = 0

        while True:
            ret, frame = cap.read()
            if not ret:
                break
            if frame_count % 3 == 0:
                frame = cv2.resize(frame, (224,224))
                frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                frame = transform(frame)
                frames.append(frame)
            frame_count += 1
            if len(frames) >= self.max_frames:
                break

        cap.release()

        if len(frames) == 0:
            frames = [torch.zeros(3, 224, 224)]

        frames = torch.stack(frames)

        tokens = [self.word2idx.get(w, self.word2idx['<unk>']) for w in sentence.split()]
        tokens = [self.word2idx['<sos>']] + tokens + [self.word2idx['<eos>']]
        target = torch.tensor(tokens)

        return frames, target


# 3️. MODEL DEFINITIONS


class CNNFeatureExtractor(nn.Module):
    def __init__(self):
        super().__init__()
        base = models.resnet18(weights=models.ResNet18_Weights.DEFAULT)
        self.features = nn.Sequential(*list(base.children())[:-1])
        self.fc = nn.Linear(base.fc.in_features, 512)

    def forward(self, x):
        batch_size, seq_len, c, h, w = x.size()
        x = x.view(batch_size*seq_len, c, h, w)
        feats = self.features(x)
        feats = feats.view(feats.size(0), -1)
        feats = self.fc(feats)
        feats = feats.view(batch_size, seq_len, -1)
        return feats

class BiLSTMEncoder(nn.Module):
    def __init__(self, input_dim=512, hidden_dim=256, num_layers=1):
        super().__init__()
        self.lstm = nn.LSTM(input_dim, hidden_dim, num_layers, batch_first=True, bidirectional=True)

    def forward(self, x):
        outputs, (h, c) = self.lstm(x)
        return outputs, (h, c)

class Attention(nn.Module):
    def __init__(self, enc_out_dim, dec_hidden_dim):
        super().__init__()
        self.attn = nn.Linear(enc_out_dim + dec_hidden_dim, dec_hidden_dim)
        self.v = nn.Linear(dec_hidden_dim, 1, bias=False)

    def forward(self, hidden, encoder_outputs):
        hidden_state = hidden.squeeze(0)
        hidden_repeated = hidden_state.unsqueeze(1).repeat(1, encoder_outputs.size(1), 1)
        combined = torch.cat((hidden_repeated, encoder_outputs), dim=2)
        energy = torch.tanh(self.attn(combined))
        attention = self.v(energy).squeeze(2)
        return torch.softmax(attention, dim=1)

class Decoder(nn.Module):
    def __init__(self, output_dim, enc_out_dim, dec_hidden_dim, dropout=0.1):
        super().__init__()
        self.embedding = nn.Embedding(output_dim, dec_hidden_dim)
        self.rnn = nn.LSTM(dec_hidden_dim + enc_out_dim, dec_hidden_dim, batch_first=True)
        self.fc_out = nn.Linear(dec_hidden_dim + enc_out_dim + dec_hidden_dim, output_dim)
        self.dropout = nn.Dropout(dropout)
        self.attention = Attention(enc_out_dim=enc_out_dim, dec_hidden_dim=dec_hidden_dim)

    def forward(self, input, hidden, cell, encoder_outputs):
        input = input.unsqueeze(1)
        embedded = self.dropout(self.embedding(input))
        attn_weights = self.attention(hidden, encoder_outputs)
        attn_weights = attn_weights.unsqueeze(1)
        weighted = torch.bmm(attn_weights, encoder_outputs)
        rnn_input = torch.cat((embedded, weighted), dim=2)
        output, (hidden, cell) = self.rnn(rnn_input, (hidden, cell))
        prediction = self.fc_out(torch.cat((output.squeeze(1), weighted.squeeze(1), embedded.squeeze(1)), dim=1))
        return prediction, hidden, cell


# 4️. TRAINING LOOP WITH ACCURACY

def train(model_components, dataloader, optimizer, criterion, clip=1.0):
    cnn, encoder, decoder = model_components
    cnn.train(); encoder.train(); decoder.train()
    epoch_loss = 0
    total_correct = 0
    total_tokens = 0

    for frames, targets in tqdm(dataloader, desc="Training"):
        max_frame_len = max(f.size(0) for f in frames)
        padded_frames = torch.zeros(len(frames), max_frame_len, frames[0].size(1), frames[0].size(2), frames[0].size(3))
        for i, f in enumerate(frames):
            padded_frames[i, :f.size(0)] = f
        frames = padded_frames.to(device)

        max_target_len = max(t.size(0) for t in targets)
        padded_targets = torch.ones(len(targets), max_target_len).long() * word2idx['<pad>']
        for i, t in enumerate(targets):
            padded_targets[i, :t.size(0)] = t
        targets = padded_targets.to(device)

        optimizer.zero_grad()
        batch_size = frames.size(0)

        cnn_feats = cnn(frames)
        enc_out, (h, c) = encoder(cnn_feats)

        hidden = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1).unsqueeze(0)
        cell = torch.cat((c[-2,:,:], c[-1,:,:]), dim=1).unsqueeze(0)

        input_token = torch.tensor([word2idx['<sos>']]*batch_size, device=device)
        loss = 0

        for t in range(1, targets.size(1)):
            output, hidden, cell = decoder(input_token, hidden, cell, enc_out)
            loss += criterion(output, targets[:,t])

            # Calculate accuracy
            predictions = output.argmax(1)
            mask = (targets[:,t] != word2idx['<pad>'])
            correct = (predictions == targets[:,t]) & mask
            total_correct += correct.sum().item()
            total_tokens += mask.sum().item()

            input_token = targets[:,t]

        loss.backward()
        torch.nn.utils.clip_grad_norm_(list(cnn.parameters()) + list(encoder.parameters()) + list(decoder.parameters()), clip)
        optimizer.step()
        epoch_loss += loss.item() / targets.size(1)

    accuracy = (total_correct / total_tokens * 100) if total_tokens > 0 else 0
    return epoch_loss / len(dataloader), accuracy


# 5️. EVALUATION WITH BLEU AND ACCURACY

def evaluate(model_components, dataloader, max_len=30):
    cnn, encoder, decoder = model_components
    cnn.eval(); encoder.eval(); decoder.eval()
    total_bleu = 0
    total_correct = 0
    total_tokens = 0
    count = 0

    with torch.no_grad():
        for frames, targets in dataloader:
            max_frame_len = max(f.size(0) for f in frames)
            padded_frames = torch.zeros(len(frames), max_frame_len, frames[0].size(1), frames[0].size(2), frames[0].size(3))
            for i, f in enumerate(frames):
                padded_frames[i, :f.size(0)] = f
            frames = padded_frames.to(device)

            batch_size = frames.size(0)

            cnn_feats = cnn(frames)
            enc_out, (h, c) = encoder(cnn_feats)

            hidden = torch.cat((h[-2,:,:], h[-1,:,:]), dim=1).unsqueeze(0)
            cell = torch.cat((c[-2,:,:], c[-1,:,:]), dim=1).unsqueeze(0)

            input_token = torch.tensor([word2idx['<sos>']]*batch_size, device=device)
            outputs_batch = []

            for t in range(max_len):
                output, hidden, cell = decoder(input_token, hidden, cell, enc_out)
                top1 = output.argmax(1)

                # Calculate token-level accuracy for valid positions
                if t < targets[0].size(0) - 1:
                    for i in range(batch_size):
                        if t + 1 < targets[i].size(0):
                            true_token = targets[i][t + 1]
                            if true_token != word2idx['<pad>']:
                                if top1[i] == true_token:
                                    total_correct += 1
                                total_tokens += 1

                if top1[0].item() == word2idx["<eos>"]:
                    break
                outputs_batch.append(top1)
                input_token = top1

            if len(outputs_batch) > 0:
                outputs_batch = torch.stack(outputs_batch, dim=1)
            else:
                outputs_batch = torch.tensor([[]], device=device, dtype=torch.long)

            for i in range(batch_size):
                if outputs_batch.numel() > 0:
                    pred_tokens = [idx2word[idx.item()] if idx.item() < len(idx2word) else "<unk>"
                                   for idx in outputs_batch[i]
                                   if idx.item() not in [word2idx['<pad>'], word2idx['<eos>']]]
                else:
                    pred_tokens = []

                true_tokens = [idx2word[idx.item()] if idx.item() < len(idx2word) else "<unk>"
                               for idx in targets[i][1:]
                               if idx.item() not in [word2idx['<pad>'], word2idx['<eos>']]]

                if true_tokens and pred_tokens:
                    bleu_score = sentence_bleu([true_tokens], pred_tokens, weights=(0.5,0.5))
                    total_bleu += bleu_score
                    count += 1

    avg_bleu = total_bleu / max(1, count)
    accuracy = (total_correct / total_tokens * 100) if total_tokens > 0 else 0
    return avg_bleu, accuracy


# 6️. VISUALIZATION FUNCTIONS

def plot_training_metrics(train_losses, train_bleus, train_accs, eval_bleus, eval_accs, save_path='training_metrics.png'):
    """Plot training metrics: Loss, BLEU, and Accuracy"""

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    epochs = range(1, len(train_losses) + 1)

    # Plot 1: Training Loss
    axes[0].plot(epochs, train_losses, 'b-o', linewidth=2, markersize=6, label='Training Loss')
    axes[0].set_xlabel('Epoch', fontsize=12, fontweight='bold')
    axes[0].set_ylabel('Loss', fontsize=12, fontweight='bold')
    axes[0].set_title('Training Loss vs Epochs', fontsize=14, fontweight='bold')
    axes[0].grid(True, alpha=0.3)
    axes[0].legend(fontsize=10)

    # Plot 2: BLEU Score
    axes[1].plot(epochs, train_bleus, 'g-o', linewidth=2, markersize=6, label='Train BLEU')
    axes[1].plot(epochs, eval_bleus, 'r-s', linewidth=2, markersize=6, label='Eval BLEU')
    axes[1].set_xlabel('Epoch', fontsize=12, fontweight='bold')
    axes[1].set_ylabel('BLEU Score', fontsize=12, fontweight='bold')
    axes[1].set_title('BLEU Score vs Epochs', fontsize=14, fontweight='bold')
    axes[1].grid(True, alpha=0.3)
    axes[1].legend(fontsize=10)

    # Plot 3: Accuracy
    axes[2].plot(epochs, train_accs, 'purple', marker='o', linewidth=2, markersize=6, label='Train Accuracy')
    axes[2].plot(epochs, eval_accs, 'orange', marker='s', linewidth=2, markersize=6, label='Eval Accuracy')
    axes[2].set_xlabel('Epoch', fontsize=12, fontweight='bold')
    axes[2].set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
    axes[2].set_title('Accuracy vs Epochs', fontsize=14, fontweight='bold')
    axes[2].grid(True, alpha=0.3)
    axes[2].legend(fontsize=10)

    plt.tight_layout()
    plt.savefig(save_path, dpi=300, bbox_inches='tight')
    print(f"\n Training metrics plot saved to: {save_path}")
    plt.show()

def save_metrics_to_file(train_losses, train_bleus, train_accs, eval_bleus, eval_accs, filepath='training_metrics.txt'):
    """Save all metrics to a text file"""
    with open(filepath, 'w') as f:
        f.write("TRAINING METRICS SUMMARY\n")


        f.write(f"{'Epoch':<8} {'Train Loss':<15} {'Train BLEU':<15} {'Train Acc':<15} {'Eval BLEU':<15} {'Eval Acc':<15}\n")
        f.write("-"*90 + "\n")

        for i in range(len(train_losses)):
            f.write(f"{i+1:<8} {train_losses[i]:<15.4f} {train_bleus[i]:<15.4f} {train_accs[i]:<15.2f} {eval_bleus[i]:<15.4f} {eval_accs[i]:<15.2f}\n")

        f.write("BEST METRICS\n")

        f.write(f"Best Train Loss: {min(train_losses):.4f} (Epoch {train_losses.index(min(train_losses))+1})\n")
        f.write(f"Best Train BLEU: {max(train_bleus):.4f} (Epoch {train_bleus.index(max(train_bleus))+1})\n")
        f.write(f"Best Train Accuracy: {max(train_accs):.2f}% (Epoch {train_accs.index(max(train_accs))+1})\n")
        f.write(f"Best Eval BLEU: {max(eval_bleus):.4f} (Epoch {eval_bleus.index(max(eval_bleus))+1})\n")
        f.write(f"Best Eval Accuracy: {max(eval_accs):.2f}% (Epoch {eval_accs.index(max(eval_accs))+1})\n")

    print(f" Metrics saved to: {filepath}")

# 7️. RUN TRAINING WITH VISUALIZATION

if __name__ == "__main__":
    def custom_collate_fn(batch):
        frames, targets = zip(*batch)
        return list(frames), list(targets)

    dataset = PhoenixDataset(VIDEO_DIR, annotation_samples, word2idx)

    if len(dataset) == 0:
        print("\n ERROR: No valid samples in dataset. Cannot proceed with training.")
        print("\nTroubleshooting steps:")
        print("1. Check annotation file format (should be pickled gzip)")
        print("2. Verify video files exist in VIDEO_DIR")
        print("3. Ensure video names in annotations match actual filenames")
    else:
        dataloader = DataLoader(dataset, batch_size=2, shuffle=True, num_workers=2, collate_fn=custom_collate_fn)

        cnn = CNNFeatureExtractor().to(device)
        encoder = BiLSTMEncoder(input_dim=512, hidden_dim=256).to(device)
        decoder = Decoder(len(word2idx), enc_out_dim=512, dec_hidden_dim=512).to(device)

        optimizer = optim.AdamW(list(cnn.parameters()) + list(encoder.parameters()) + list(decoder.parameters()), lr=1e-4)
        criterion = nn.CrossEntropyLoss(ignore_index=word2idx['<pad>'])

        # Lists to store metrics
        train_losses = []
        train_bleus = []
        train_accs = []
        eval_bleus = []
        eval_accs = []

        epochs = 40
        print("STARTING TRAINING")

        for epoch in range(epochs):
            print(f"Epoch {epoch+1}/{epochs}")

            # Training
            train_loss, train_acc = train((cnn, encoder, decoder), dataloader, optimizer, criterion)
            train_bleu, _ = evaluate((cnn, encoder, decoder), dataloader)

            # Evaluation
            eval_bleu, eval_acc = evaluate((cnn, encoder, decoder), dataloader)

            # Store metrics
            train_losses.append(train_loss)
            train_bleus.append(train_bleu)
            train_accs.append(train_acc)
            eval_bleus.append(eval_bleu)
            eval_accs.append(eval_acc)

            # Print metrics
            print(f"\n Epoch {epoch+1}/{epochs} Results:")
            print(f"   Train Loss: {train_loss:.4f}")
            print(f"   Train BLEU: {train_bleu:.4f}")
            print(f"   Train Accuracy: {train_acc:.2f}%")
            print(f"   Eval BLEU: {eval_bleu:.4f}")
            print(f"   Eval Accuracy: {eval_acc:.2f}%")

            # Save checkpoint every 10 epochs
            if (epoch + 1) % 10 == 0:
                checkpoint_path = f'checkpoint_epoch_{epoch+1}.pt'
                torch.save({
                    'epoch': epoch + 1,
                    'cnn_state_dict': cnn.state_dict(),
                    'encoder_state_dict': encoder.state_dict(),
                    'decoder_state_dict': decoder.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'train_loss': train_loss,
                    'train_bleu': train_bleu,
                    'train_acc': train_acc,
                }, checkpoint_path)
                print(f"   Checkpoint saved: {checkpoint_path}")

        # Final results
        print("TRAINING COMPLETED!")
        print(f"\n BEST RESULTS:")
        print(f"   Best Train Loss: {min(train_losses):.4f} (Epoch {train_losses.index(min(train_losses))+1})")
        print(f"   Best Train BLEU: {max(train_bleus):.4f} (Epoch {train_bleus.index(max(train_bleus))+1})")
        print(f"   Best Train Accuracy: {max(train_accs):.2f}% (Epoch {train_accs.index(max(train_accs))+1})")
        print(f"   Best Eval BLEU: {max(eval_bleus):.4f} (Epoch {eval_bleus.index(max(eval_bleus))+1})")
        print(f"   Best Eval Accuracy: {max(eval_accs):.2f}% (Epoch {eval_accs.index(max(eval_accs))+1})")

        # Plot and save metrics
        plot_training_metrics(train_losses, train_bleus, train_accs, eval_bleus, eval_accs)
        save_metrics_to_file(train_losses, train_bleus, train_accs, eval_bleus, eval_accs)

        # Save final model
        final_model_path = 'final_model.pt'
        torch.save({
            'cnn_state_dict': cnn.state_dict(),
            'encoder_state_dict': encoder.state_dict(),
            'decoder_state_dict': decoder.state_dict(),
            'word2idx': word2idx,
            'idx2word': idx2word,
            'final_metrics': {
                'train_loss': train_losses[-1],
                'train_bleu': train_bleus[-1],
                'train_acc': train_accs[-1],
                'eval_bleu': eval_bleus[-1],
                'eval_acc': eval_accs[-1],
            }
        }, final_model_path)
        print(f"\n Final model saved to: {final_model_path}")

"""
PHOENIX14T SIGN LANGUAGE TRANSLATION - TRAINING VISUALIZATION
Optimized for Google Colab
Copy and paste this entire code into a Colab cell and run!
"""

import matplotlib.pyplot as plt
import numpy as np

# ============================================================================
# TRAINING DATA (Epochs 1-39 from your training output)
# ============================================================================

epochs = list(range(1, 40))

train_losses = [
    6.6741, 4.7183, 4.2646, 4.0115, 3.6801, 3.4764, 3.2696, 3.0447, 2.8353, 2.6090,
    2.3865, 2.2122, 2.0643, 1.8716, 1.7305, 1.5792, 1.4252, 1.2920, 1.1752, 1.0975,
    0.9671, 0.8829, 0.8029, 0.7209, 0.6711, 0.6139, 0.5500, 0.5040, 0.4632, 0.4094,
    0.3724, 0.3449, 0.3131, 0.2779, 0.2506, 0.2265, 0.2029, 0.1793, 0.1592
]

train_bleus = [
    0.0000, 0.0000, 0.0209, 0.0228, 0.0519, 0.0588, 0.0555, 0.0585, 0.0625, 0.0760,
    0.0600, 0.0789, 0.0719, 0.0787, 0.0702, 0.0890, 0.0784, 0.0882, 0.1008, 0.0937,
    0.1125, 0.1306, 0.1942, 0.1576, 0.2054, 0.2121, 0.3177, 0.2541, 0.3336, 0.3267,
    0.4373, 0.4504, 0.5712, 0.6461, 0.6433, 0.6170, 0.6854, 0.7197, 0.7723
]

train_accs = [
    6.10, 13.42, 16.85, 20.48, 22.19, 23.90, 27.12, 29.18, 31.92, 36.03,
    40.48, 43.97, 51.23, 56.99, 61.23, 65.55, 71.58, 74.25, 76.99, 79.79,
    82.40, 84.18, 86.44, 88.22, 88.56, 89.38, 91.64, 91.85, 92.81, 93.56,
    94.52, 94.52, 95.41, 95.62, 97.40, 96.92, 97.88, 97.81, 98.63
]

eval_bleus = [
    0.0000, 0.0000, 0.0209, 0.0203, 0.0505, 0.0604, 0.0536, 0.0621, 0.0617, 0.0765,
    0.0614, 0.0657, 0.0831, 0.0789, 0.0724, 0.0932, 0.0885, 0.0839, 0.0845, 0.1039,
    0.1275, 0.1454, 0.1575, 0.1686, 0.1846, 0.1985, 0.2804, 0.2567, 0.3151, 0.3330,
    0.4150, 0.4670, 0.5425, 0.5882, 0.6870, 0.6207, 0.6769, 0.7186, 0.7560
]

eval_accs = [
    4.67, 6.68, 5.20, 7.55, 6.39, 5.95, 6.57, 7.66, 6.88, 11.34,
    8.69, 8.81, 10.99, 9.30, 10.45, 11.56, 11.48, 11.52, 12.51, 11.12,
    15.61, 18.72, 18.15, 21.48, 21.19, 23.30, 30.63, 27.97, 37.34, 39.83,
    44.25, 58.24, 61.55, 72.06, 78.74, 73.58, 78.25, 88.50, 88.53
]

# ============================================================================
# FIGURE 1: COMPREHENSIVE TRAINING ANALYSIS (6 PLOTS)
# ============================================================================

print("🎨 Generating comprehensive training analysis graphs...")

fig = plt.figure(figsize=(20, 12))

# 1. Training Loss Over Time
ax1 = plt.subplot(2, 3, 1)
ax1.plot(epochs, train_losses, 'b-o', linewidth=2.5, markersize=5, label='Training Loss', alpha=0.8)
ax1.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax1.set_ylabel('Loss', fontsize=13, fontweight='bold')
ax1.set_title('Training Loss Progression', fontsize=15, fontweight='bold', pad=15)
ax1.grid(True, alpha=0.3, linestyle='--')
ax1.legend(fontsize=11, loc='upper right')
ax1.set_xlim(0, 40)

# Add trend line
z = np.polyfit(epochs, train_losses, 3)
p = np.poly1d(z)
ax1.plot(epochs, p(epochs), "r--", alpha=0.5, linewidth=1.5, label='Trend')

# 2. BLEU Score Comparison
ax2 = plt.subplot(2, 3, 2)
ax2.plot(epochs, train_bleus, 'g-o', linewidth=2.5, markersize=5, label='Train BLEU', alpha=0.8)
ax2.plot(epochs, eval_bleus, 'r-s', linewidth=2.5, markersize=5, label='Eval BLEU', alpha=0.8)
ax2.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax2.set_ylabel('BLEU Score', fontsize=13, fontweight='bold')
ax2.set_title('BLEU Score: Train vs Eval', fontsize=15, fontweight='bold', pad=15)
ax2.grid(True, alpha=0.3, linestyle='--')
ax2.legend(fontsize=11, loc='upper left')
ax2.set_xlim(0, 40)

# 3. Accuracy Comparison
ax3 = plt.subplot(2, 3, 3)
ax3.plot(epochs, train_accs, 'purple', marker='o', linewidth=2.5, markersize=5, label='Train Accuracy', alpha=0.8)
ax3.plot(epochs, eval_accs, 'orange', marker='s', linewidth=2.5, markersize=5, label='Eval Accuracy', alpha=0.8)
ax3.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax3.set_ylabel('Accuracy (%)', fontsize=13, fontweight='bold')
ax3.set_title('Accuracy: Train vs Eval', fontsize=15, fontweight='bold', pad=15)
ax3.grid(True, alpha=0.3, linestyle='--')
ax3.legend(fontsize=11, loc='upper left')
ax3.set_xlim(0, 40)

# 4. All Metrics Combined (Normalized)
ax4 = plt.subplot(2, 3, 4)
# Normalize metrics to 0-1 scale for comparison
norm_loss = [(max(train_losses) - x) / (max(train_losses) - min(train_losses)) for x in train_losses]
norm_train_bleu = [x / max(train_bleus) for x in train_bleus]
norm_eval_bleu = [x / max(eval_bleus) for x in eval_bleus]
norm_train_acc = [x / max(train_accs) for x in train_accs]
norm_eval_acc = [x / max(eval_accs) for x in eval_accs]

ax4.plot(epochs, norm_loss, 'b-', linewidth=2, label='Loss (inverted)', alpha=0.7)
ax4.plot(epochs, norm_train_bleu, 'g-', linewidth=2, label='Train BLEU', alpha=0.7)
ax4.plot(epochs, norm_eval_bleu, 'r-', linewidth=2, label='Eval BLEU', alpha=0.7)
ax4.plot(epochs, norm_train_acc, 'purple', linewidth=2, label='Train Acc', alpha=0.7)
ax4.plot(epochs, norm_eval_acc, 'orange', linewidth=2, label='Eval Acc', alpha=0.7)
ax4.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax4.set_ylabel('Normalized Score (0-1)', fontsize=13, fontweight='bold')
ax4.set_title('All Metrics Normalized', fontsize=15, fontweight='bold', pad=15)
ax4.grid(True, alpha=0.3, linestyle='--')
ax4.legend(fontsize=10, loc='lower right')
ax4.set_xlim(0, 40)

# 5. Train vs Eval Gap Analysis
ax5 = plt.subplot(2, 3, 5)
bleu_gap = [train_bleus[i] - eval_bleus[i] for i in range(len(epochs))]
acc_gap = [train_accs[i] - eval_accs[i] for i in range(len(epochs))]

ax5_twin = ax5.twinx()
ax5.bar(epochs, bleu_gap, alpha=0.6, color='green', label='BLEU Gap', width=0.8)
ax5_twin.plot(epochs, acc_gap, 'ro-', linewidth=2, markersize=4, label='Accuracy Gap', alpha=0.8)

ax5.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax5.set_ylabel('BLEU Gap (Train - Eval)', fontsize=12, fontweight='bold', color='green')
ax5_twin.set_ylabel('Accuracy Gap (%)', fontsize=12, fontweight='bold', color='red')
ax5.set_title('Overfitting Analysis: Train-Eval Gap', fontsize=15, fontweight='bold', pad=15)
ax5.grid(True, alpha=0.3, linestyle='--')
ax5.tick_params(axis='y', labelcolor='green')
ax5_twin.tick_params(axis='y', labelcolor='red')
ax5.axhline(y=0, color='black', linestyle='--', linewidth=1, alpha=0.5)
ax5.set_xlim(0, 40)

# 6. Learning Rate Analysis (Improvement per epoch)
ax6 = plt.subplot(2, 3, 6)
loss_improvement = [-1 * (train_losses[i] - train_losses[i-1]) for i in range(1, len(train_losses))]
bleu_improvement = [(eval_bleus[i] - eval_bleus[i-1]) for i in range(1, len(eval_bleus))]
acc_improvement = [(eval_accs[i] - eval_accs[i-1]) for i in range(1, len(eval_accs))]

ax6.plot(epochs[1:], loss_improvement, 'b-o', linewidth=2, markersize=4, label='Loss Decrease', alpha=0.7)
ax6_twin = ax6.twinx()
ax6_twin.plot(epochs[1:], bleu_improvement, 'g-s', linewidth=2, markersize=4, label='BLEU Increase', alpha=0.7)
ax6_twin.plot(epochs[1:], acc_improvement, 'r-^', linewidth=2, markersize=4, label='Acc Increase', alpha=0.7)

ax6.set_xlabel('Epoch', fontsize=13, fontweight='bold')
ax6.set_ylabel('Loss Improvement', fontsize=12, fontweight='bold', color='blue')
ax6_twin.set_ylabel('BLEU/Acc Improvement', fontsize=12, fontweight='bold', color='green')
ax6.set_title('Per-Epoch Improvement Rate', fontsize=15, fontweight='bold', pad=15)
ax6.grid(True, alpha=0.3, linestyle='--')
ax6.tick_params(axis='y', labelcolor='blue')
ax6_twin.tick_params(axis='y', labelcolor='green')
ax6.axhline(y=0, color='black', linestyle='--', linewidth=1, alpha=0.5)
ax6.set_xlim(0, 40)
lines1, labels1 = ax6.get_legend_handles_labels()
lines2, labels2 = ax6_twin.get_legend_handles_labels()
ax6_twin.legend(lines1 + lines2, labels1 + labels2, fontsize=10, loc='upper right')

plt.suptitle('Phoenix14T Sign Language Translation - Complete Training Analysis (40 Epochs)',
             fontsize=18, fontweight='bold', y=0.995)

plt.tight_layout()
plt.savefig('comprehensive_training_comparison.png', dpi=300, bbox_inches='tight')
print("✅ Figure 1 saved: comprehensive_training_comparison.png")
plt.show()

# ============================================================================
# FIGURE 2: MILESTONE COMPARISONS (4 PLOTS)
# ============================================================================

print("\n🎨 Generating milestone comparison graphs...")

fig2, axes = plt.subplots(2, 2, figsize=(16, 12))

# Milestone epochs
milestones = [1, 10, 20, 30, 39]
milestone_labels = ['Epoch 1', 'Epoch 10', 'Epoch 20', 'Epoch 30', 'Epoch 39']

# Extract milestone data
milestone_train_bleu = [train_bleus[i-1] for i in milestones]
milestone_eval_bleu = [eval_bleus[i-1] for i in milestones]
milestone_train_acc = [train_accs[i-1] for i in milestones]
milestone_eval_acc = [eval_accs[i-1] for i in milestones]
milestone_loss = [train_losses[i-1] for i in milestones]

# Plot 1: BLEU Score Milestones
x_pos = np.arange(len(milestones))
width = 0.35
axes[0, 0].bar(x_pos - width/2, milestone_train_bleu, width, label='Train BLEU', color='green', alpha=0.8)
axes[0, 0].bar(x_pos + width/2, milestone_eval_bleu, width, label='Eval BLEU', color='red', alpha=0.8)
axes[0, 0].set_xlabel('Training Milestone', fontsize=12, fontweight='bold')
axes[0, 0].set_ylabel('BLEU Score', fontsize=12, fontweight='bold')
axes[0, 0].set_title('BLEU Score at Key Milestones', fontsize=14, fontweight='bold')
axes[0, 0].set_xticks(x_pos)
axes[0, 0].set_xticklabels(milestone_labels)
axes[0, 0].legend(fontsize=11)
axes[0, 0].grid(True, alpha=0.3, axis='y')

# Add value labels on bars
for i, (v1, v2) in enumerate(zip(milestone_train_bleu, milestone_eval_bleu)):
    axes[0, 0].text(i - width/2, v1 + 0.01, f'{v1:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')
    axes[0, 0].text(i + width/2, v2 + 0.01, f'{v2:.3f}', ha='center', va='bottom', fontsize=9, fontweight='bold')

# Plot 2: Accuracy Milestones
axes[0, 1].bar(x_pos - width/2, milestone_train_acc, width, label='Train Acc', color='purple', alpha=0.8)
axes[0, 1].bar(x_pos + width/2, milestone_eval_acc, width, label='Eval Acc', color='orange', alpha=0.8)
axes[0, 1].set_xlabel('Training Milestone', fontsize=12, fontweight='bold')
axes[0, 1].set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
axes[0, 1].set_title('Accuracy at Key Milestones', fontsize=14, fontweight='bold')
axes[0, 1].set_xticks(x_pos)
axes[0, 1].set_xticklabels(milestone_labels)
axes[0, 1].legend(fontsize=11)
axes[0, 1].grid(True, alpha=0.3, axis='y')

# Add value labels
for i, (v1, v2) in enumerate(zip(milestone_train_acc, milestone_eval_acc)):
    axes[0, 1].text(i - width/2, v1 + 1, f'{v1:.1f}%', ha='center', va='bottom', fontsize=9, fontweight='bold')
    axes[0, 1].text(i + width/2, v2 + 1, f'{v2:.1f}%', ha='center', va='bottom', fontsize=9, fontweight='bold')

# Plot 3: Loss Decrease
axes[1, 0].plot(milestones, milestone_loss, 'b-o', linewidth=3, markersize=10, alpha=0.8)
axes[1, 0].fill_between(milestones, milestone_loss, alpha=0.3)
axes[1, 0].set_xlabel('Training Milestone', fontsize=12, fontweight='bold')
axes[1, 0].set_ylabel('Training Loss', fontsize=12, fontweight='bold')
axes[1, 0].set_title('Loss Reduction Progress', fontsize=14, fontweight='bold')
axes[1, 0].set_xticks(milestones)
axes[1, 0].set_xticklabels(milestone_labels)
axes[1, 0].grid(True, alpha=0.3)
axes[1, 0].invert_yaxis()  # Lower loss is better

# Add value labels
for i, (x, y) in enumerate(zip(milestones, milestone_loss)):
    axes[1, 0].text(x, y, f'{y:.3f}', ha='center', va='top', fontsize=10, fontweight='bold')

# Plot 4: Overall Improvement Summary
metrics = ['BLEU\nScore', 'Accuracy\n(%)', 'Loss\nReduction']
start_values = [eval_bleus[0], eval_accs[0], train_losses[0]]
end_values = [eval_bleus[-1], eval_accs[-1], train_losses[-1]]
improvement = [
    ((eval_bleus[-1] - eval_bleus[0]) / max(eval_bleus[0], 0.001)) * 100,
    ((eval_accs[-1] - eval_accs[0]) / max(eval_accs[0], 0.001)) * 100,
    ((train_losses[0] - train_losses[-1]) / train_losses[0]) * 100
]

x_pos2 = np.arange(len(metrics))
colors = ['green', 'orange', 'blue']
bars = axes[1, 1].bar(x_pos2, improvement, color=colors, alpha=0.8, edgecolor='black', linewidth=2)
axes[1, 1].set_ylabel('Improvement (%)', fontsize=12, fontweight='bold')
axes[1, 1].set_title('Overall Improvement (Epoch 1 → 39)', fontsize=14, fontweight='bold')
axes[1, 1].set_xticks(x_pos2)
axes[1, 1].set_xticklabels(metrics, fontsize=11)
axes[1, 1].grid(True, alpha=0.3, axis='y')

# Add value labels
for i, (bar, val) in enumerate(zip(bars, improvement)):
    height = bar.get_height()
    axes[1, 1].text(bar.get_x() + bar.get_width()/2., height + 50,
                    f'+{val:.0f}%', ha='center', va='bottom', fontsize=12, fontweight='bold')
    # Add start and end values
    axes[1, 1].text(bar.get_x() + bar.get_width()/2., -100,
                    f'{start_values[i]:.3f}→{end_values[i]:.3f}',
                    ha='center', va='top', fontsize=9, style='italic')

plt.suptitle('Training Milestones & Overall Improvement Summary',
             fontsize=18, fontweight='bold', y=0.995)

plt.tight_layout()
plt.savefig('milestone_comparison.png', dpi=300, bbox_inches='tight')
print("✅ Figure 2 saved: milestone_comparison.png")
plt.show()

# ============================================================================
# FIGURE 3: SIMPLE 3-PANEL VIEW (Clean and Clear)
# ============================================================================

print("\n🎨 Generating simple 3-panel comparison...")

fig3, axes3 = plt.subplots(1, 3, figsize=(18, 5))

# Panel 1: Training Loss
axes3[0].plot(epochs, train_losses, 'b-o', linewidth=2.5, markersize=6, label='Training Loss')
axes3[0].set_xlabel('Epoch', fontsize=12, fontweight='bold')
axes3[0].set_ylabel('Loss', fontsize=12, fontweight='bold')
axes3[0].set_title('Training Loss vs Epochs', fontsize=14, fontweight='bold')
axes3[0].grid(True, alpha=0.3)
axes3[0].legend(fontsize=11)

# Panel 2: BLEU Score
axes3[1].plot(epochs, train_bleus, 'g-o', linewidth=2.5, markersize=6, label='Train BLEU')
axes3[1].plot(epochs, eval_bleus, 'r-s', linewidth=2.5, markersize=6, label='Eval BLEU')
axes3[1].set_xlabel('Epoch', fontsize=12, fontweight='bold')
axes3[1].set_ylabel('BLEU Score', fontsize=12, fontweight='bold')
axes3[1].set_title('BLEU Score vs Epochs', fontsize=14, fontweight='bold')
axes3[1].grid(True, alpha=0.3)
axes3[1].legend(fontsize=11)

# Panel 3: Accuracy
axes3[2].plot(epochs, train_accs, 'purple', marker='o', linewidth=2.5, markersize=6, label='Train Accuracy')
axes3[2].plot(epochs, eval_accs, 'orange', marker='s', linewidth=2.5, markersize=6, label='Eval Accuracy')
axes3[2].set_xlabel('Epoch', fontsize=12, fontweight='bold')
axes3[2].set_ylabel('Accuracy (%)', fontsize=12, fontweight='bold')
axes3[2].set_title('Accuracy vs Epochs', fontsize=14, fontweight='bold')
axes3[2].grid(True, alpha=0.3)
axes3[2].legend(fontsize=11)

plt.tight_layout()
plt.savefig('simple_training_metrics.png', dpi=300, bbox_inches='tight')
print("✅ Figure 3 saved: simple_training_metrics.png")
plt.show()

# ============================================================================
# PRINT SUMMARY STATISTICS
# ============================================================================

print("\n" + "="*70)
print("📊 TRAINING SUMMARY STATISTICS")
print("="*70)
print(f"\n🎯 FINAL RESULTS (Epoch 39):")
print(f"   • Training Loss:      {train_losses[-1]:.4f}")
print(f"   • Training BLEU:      {train_bleus[-1]:.4f}")
print(f"   • Training Accuracy:  {train_accs[-1]:.2f}%")
print(f"   • Eval BLEU:          {eval_bleus[-1]:.4f}")
print(f"   • Eval Accuracy:      {eval_accs[-1]:.2f}%")

print(f"\n🏆 BEST PERFORMANCES:")
print(f"   • Best Train Loss:    {min(train_losses):.4f} (Epoch {train_losses.index(min(train_losses))+1})")
print(f"   • Best Train BLEU:    {max(train_bleus):.4f} (Epoch {train_bleus.index(max(train_bleus))+1})")
print(f"   • Best Train Acc:     {max(train_accs):.2f}% (Epoch {train_accs.index(max(train_accs))+1})")
print(f"   • Best Eval BLEU:     {max(eval_bleus):.4f} (Epoch {eval_bleus.index(max(eval_bleus))+1})")
print(f"   • Best Eval Acc:      {max(eval_accs):.2f}% (Epoch {eval_accs.index(max(eval_accs))+1})")

print(f"\n📈 TOTAL IMPROVEMENT:")
print(f"   • Loss Reduction:     {train_losses[0]:.4f} → {train_losses[-1]:.4f} ({((train_losses[0]-train_losses[-1])/train_losses[0]*100):.1f}% decrease)")
print(f"   • BLEU Improvement:   {eval_bleus[0]:.4f} → {eval_bleus[-1]:.4f} (Infinite % - started from 0)")
print(f"   • Acc Improvement:    {eval_accs[0]:.2f}% → {eval_accs[-1]:.2f}% (+{eval_accs[-1]-eval_accs[0]:.2f} points)")

print(f"\n🔍 OVERFITTING ANALYSIS:")
final_bleu_gap = train_bleus[-1] - eval_bleus[-1]
final_acc_gap = train_accs[-1] - eval_accs[-1]
print(f"   • Final BLEU Gap:     {final_bleu_gap:.4f} (Train - Eval)")
print(f"   • Final Acc Gap:      {final_acc_gap:.2f}% (Train - Eval)")
if final_bleu_gap < 0.05 and final_acc_gap < 15:
    print(f"   ✅ Status: Good generalization!")
elif final_bleu_gap < 0.1 and final_acc_gap < 25:
    print(f"   ⚠️  Status: Moderate overfitting")
else:
    print(f"   ⚠️  Status: Significant overfitting detected")

print("\n" + "="*70)
print("✅ ALL GRAPHS GENERATED SUCCESSFULLY!")
print("="*70)
print("\n📁 Files saved:")
print("   1. comprehensive_training_comparison.png")
print("   2. milestone_comparison.png")
print("   3. simple_training_metrics.png")
print("\n💡 Tip: In Colab, images will display inline. Use files.download() to save them.")
print("="*70)